name: Build WebGl
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build All Platforms"]
    types:
      - completed

jobs:
  buildWebGL:
    name: Build for WebGL
    runs-on: ubuntu-latest
    # This stops builds that are in-progress once a new commit comes in
    steps:
      # Cleanup Docker
      - name: Cleanup Docker
        run: docker system prune --all --force --volumes

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  

      # Cleanup unnecessary files
      - name: Cleanup
        run: |
          # Remove any temporary files or old build artifacts
          rm -rf build/webgl/*

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library

      # Build WebGL
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildsPath: build/webgl 
          allowDirtyBuild: true

      # Output WebGL
      - name: Upload WebGL build artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebGLBuild
          path: build/webgl

  deployWebGL:
    name: Deploy for WebGL
    needs: buildWebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download WebGL build artifact
        uses: actions/download-artifact@v3
        with:
          name: WebGLBuild
          path: build/webgl
      - name: Deploy WebGL
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: webgl  
          ITCH_GAME: paper-people
          ITCH_USER: briggadier
          PACKAGE: build/webgl
