name: Build Windows and Publish To Itch.io
on:
    workflow_dispatch: {}
jobs:
  buildWindows:
    name: Build and publish for Windows
    runs-on: ubuntu-latest
    # This stops builds that are in-progress once a new commit comes in
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library

           # Cleanup unnecessary files
      - name: Cleanup
        run: |
          # Remove any temporary files or old build artifacts
          rm -rf build/windows/*

      # Build
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildsPath: build/windows
          
      # Output Windows
      - uses: actions/upload-artifact@v3
        with:
          name: WindowsBuild
          path: build/windows

      # Set variables for version tagging
      - name: Set release date
        run: echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Set short hash
        run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}

      # Deploy for Windows
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: paper-people
          ITCH_USER: briggadier
          PACKAGE: build/windows
          VERSION: ${{ env.RELEASE_DATE }}-${{ env.SHORT_HASH }} 
